### PR TITLE
fixed issue where time is a number

### PR DESCRIPTION
**Pull request by joeyjiron06**
Great repo! We've been using this for a couple of weeks and it works great!  We are relying on this for a local development. The issue that we are currently facing is that even though our logs have a timestamp, they all get the default timestamp from this library because time is a number in our logs. 

**Summary of changes**

- Copied this PR https://github.com/pinojs/pino-elasticsearch/pull/32
- And added unit tests as you requested

How fast can you get a new release out with this fix?

### CODE REVIEW

**Comment by joeyjiron06** [comment]
awesome, not sure why the build failed, i see this error. mind taking a look?

```
resolvconf
11.40s$ travis_apt_get_update
Installing APT Packages
0.48s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install oracle-java9-installer
Reading package lists...
Building dependency tree...
Reading state information...
Package oracle-java9-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'oracle-java9-installer' has no installation candidate
apt-get.diagnostics
apt-get install failed
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install oracle-java9-installer" failed and exited with 100 during .
Your build has been stopped.
```

**Comment by joeyjiron06** [comment]
any update on getting this build issue fixed?

**Comment by joeyjiron06** [comment]
hey, can i get an update on this? see my coment above about logs

**Comment by mcollina** [comment]
Would you mind rebasing on top of master? I think I have sorted all the CI issues.

**Comment by joeyjiron06** [comment]
Will do

**Comment by joeyjiron06** [comment]
updated, let me know when you merge it in. we are waiting for this :)

**Pull request merged**
