### PR TITLE
Elastic connection resurrect on split destroy

### PR DESCRIPTION
**Pull request by jurosm**
This resurrects elastic connection pool in case elastic server is down or the connection is broken for some reason.

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for opening a PR! Can you please add a unit test?

**Comment by jurosm** [comment]
> Thanks for opening a PR! Can you please add a unit test?

Glad to contribute! Sure I will add a unit test for this. 👍

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by KillenX** [comment]
Bump for interest

**Comment by penumbra23** [comment]
@mcollina Merging anytime soon?

**Pull request merged**
