### PR TITLE
Datastream support using op_type create config

### PR DESCRIPTION
**Pull request by FlyingWraptor**
This PR allows users to specify the datastream name as the index and set the op_type to create.
AFAIK this doesn't break any existing functionality.

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you please add a unit test?

**Review by mcollina — APPROVED** [review]
lgtm

**Review by delvedor — APPROVED** [review]
LGTM

**Comment by mcollina** [comment]
@FlyingWraptor tests seem to be failing :(

**Comment by FlyingWraptor** [comment]
Yep, I'll look into it, node incompatibilities. Can't get my acceptance test to work though it works in my production deployment ¯\_(ツ)_/¯

**Comment by FlyingWraptor** [comment]
That should be it, tests are running fine and I'm happy with the result. I added an exclusion for tests running elasicsearch < 7.9.0

**Pull request merged**
